name: MLLibrary
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - hmatrix
  - random
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Mllibrary
  default-extensions:
    - FlexibleContexts
    - MultiParamTypeClasses
    - ScopedTypeVariables

executables:
  mlmain:
    main: Main.hs
    source-dirs: app
    dependencies:
      - MLLibrary
      - hmatrix
    default-extensions:
      - FlexibleContexts